### ISSUE TITLE
Rewrite to use actual async_hooks

### ISSUE THREAD

**Issue by Fishrock123** [AndreasMadsen/dprof#17]
See https://github.com/nodejs/node/pull/8531

I've already started on this and got it working, but there are some relational challenges with timers and some underlying resources such as the HTTP parser.

I'll probably need to fix https://github.com/AndreasMadsen/dprof/issues/16 in the process and use a flat data file by UID, and convert some of the render ordering to use that. (To deal with re-used timers...)

**Comment by AndreasMadsen** [comment]
Yes!, was thinking about this too. I have previously discovered a few bugs in `async_wrap` with `dprof`. It would be great to have it working with `async_hooks`, we might discover a few issues there too.

> I'll probably need to fix #16 in the process and use a flat data file by UID, and convert some of the render ordering to use that.

Not quite sure how #16 is related to this. It sounds like you are creating a graph rather than a tree.

**Comment by Fishrock123** [comment]
@AndreasMadsen sorry, my knowledge of data structures is not the best.

Let's put it this way:

Handles with the same ID should display on the same line in the visualizer even if they are triggered from different points.

Now, that may not make 100% sense at the current time but I'm not sure how else to display timers is a conceptual and technically correct way.

That is, if you take the same timer object, do an `insert` of it (active), unenroll it (remove it), and re-insert it it, it should _probably_ keep the same ID while firing `init -> destroy -> init`.

**Comment by AndreasMadsen** [comment]
> That is, if you take the same timer object, do an insert of it (active), unenroll it (remove it), and re-insert it it, it should probably keep the same ID while firing init -> destroy -> init.

Ah, okay. That should be fine. Though the idea of uids popping back into existence is a little confusion and perhaps dangerous.

**Comment by Fishrock123** [comment]
Take, for example, this.

The handles with the line in-between are actually the same, the timeout was created and the updated three time, from different places, causing re-insertion.

<img width="1308" alt="timers-async_hooks" src="https://cloud.githubusercontent.com/assets/1093990/18617019/0abdd94a-7d95-11e6-8e17-882c4925b5d9.png">

**Comment by AndreasMadsen** [comment]
I think my understanding of node.js timer implementation is vastly insufficient to understand how a timer can be updated without becoming a different timer. In normal JS I would write `createTimeout(timer); timer = setTimeout(fn, update)`, but obviously that is not what is going on here.

In any case it does complicate things quite a bit, because a single handle will have multiple parents (no longer a tree). However because there is still a parent-child relationship, it should be possible to visualize it like it's done now, see [Topological Sorting of a DAG](https://en.wikipedia.org/wiki/Topological_sorting).

**Comment by Fishrock123** [comment]
> I think my understanding of the node.js timer implementation is vastly insufficient to understand how a timer can be updated without becoming a different timer.

I suppose this depends on the definition of "timer".

Timers are not restricted to being `Timeouts` and can actually be any any object with an `._onTimeout = function(){}` property that is then passed to `timers.enroll()` and `timers.active()`.

--

That being said, in any timers implementation, changing the timeout duration or timeout start means re-ordering the timer in an underlying queue.

In our case, due to optimizations, changing the duration may cause a new underlying TimerWrap to be created. Changing the timeout start will not.

... etc


Perhaps it really does only make sense to fire init/destroy once for these. Not 100% sure yet.

**Comment by Fishrock123** [comment]
> Timers are not restricted to being `Timeouts` and can actually be any any object with an `._onTimeout = function(){}` property that is then passed to `timers.enroll()` and `timers.active()`.

Thus, adding to the confusion, the timer in the above picture is actually a `Socket`.

**Comment by Fishrock123** [comment]
Maybe just using the same UID without firing events for re-insertion before `destroy()` is the way to go:

<img width="627" alt="timers-maybe-better-async_wrap" src="https://cloud.githubusercontent.com/assets/1093990/18634814/9c68bcc8-7e50-11e6-9a0b-15e961750cf8.png">

(handle is orange and UID 12.)

Refs: https://github.com/nodejs/node/pull/8531#issuecomment-248002326

**Comment by Fishrock123** [comment]
#19

**Comment by AndreasMadsen** [comment]
Thanks for the work, I've landed `async_hooks` support.
