### ISSUE TITLE
Tip to avoid node heap out of memory issues

### ISSUE THREAD

**Issue by BrianAdams** [AndreasMadsen/dprof#25]
With large captures, you can have node directly invoke dprof with options to allow use of more memory.
```
gzcat dprof.json.gz | node  --max_old_space_size=4096 /usr/local/lib/node_modules/dprof/bin/dprof.js
```

**Comment by AndreasMadsen** [comment]
What can we do to improve this? Why is the capture itself not a problem?

/cc @Fishrock123

**Comment by Fishrock123** [comment]
Yeah I've come across this too, I'm not sure why it happens on the parsing end either.

**Comment by AndreasMadsen** [comment]
The the json file is only parsed to  [check the `dprof` version](https://github.com/AndreasMadsen/dprof/blob/master/bin/server.js#L41). Now that we have an online visualizer that should actually be on the client side.

**Comment by AndreasMadsen** [comment]
Do you have a test script I can try?.


I tried our recursive test which generates very big dump files:

```js
'use strict';
setImmediate(function recursive(remaining) {
  if (remaining === 0) return;
  setImmediate(recursive, remaining - 1);
}, 368999);
```

Anything bigger than `368999` and the script outputs:

```
/Users/Andreas/Sites/node_modules/dprof/dprof.js:213
    fs.writeFileSync('./dprof.json.gz', zlib.gzipSync(JSON.stringify(data)));
                                                           ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at process.writeDataFile (/Users/Andreas/Sites/node_modules/dprof/dprof.js:213:60)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
```

The uncompressed dumpfile is 256 MB, but that parses fine when running `node bin/dprof.js`.

**Comment by BrianAdams** [comment]
@AndreasMadsen here ya go!
[dprof.json.gz](https://github.com/AndreasMadsen/dprof/files/676076/dprof.json.gz)

```
Babs:orov-cockpit brian$ gzcat dprof.json.gz | dprof
server ready on http://localhost:3343

<--- Last few GCs --->

   56773 ms: Mark-sweep 1374.5 (1434.3) -> 1374.5 (1434.3) MB, 2443.5 / 0 ms [allocation failure] [GC in old space requested].
   59164 ms: Mark-sweep 1374.5 (1434.3) -> 1374.5 (1434.3) MB, 2391.0 / 0 ms [allocation failure] [GC in old space requested].
   61597 ms: Mark-sweep 1374.5 (1434.3) -> 1374.5 (1434.3) MB, 2432.5 / 0 ms [last resort gc].
   63963 ms: Mark-sweep 1374.5 (1434.3) -> 1374.5 (1434.3) MB, 2366.4 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x912fb0c9e59 <JS Object>
    1: get [/usr/local/lib/node_modules/dprof/node_modules/babel-traverse/lib/path/index.js:~76] [pc=0x294ec2c9f791] (this=0x196bcc347639 <JS Function NodePath (SharedFunctionInfo 0x31b18efbfbf9)>,_ref=0x2e48c9849951 <an Object with map 0xd9aa07c2649>)
    2: node [/usr/local/lib/node_modules/dprof/node_modules/babel-traverse/lib/index.js:~94] [pc=0x294ec23724e9] (this=0x230a3c52ec91 <JS Functio...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Abort trap: 6
```

**Comment by AndreasMadsen** [comment]
Works for me, what node version are you running?

**Comment by AndreasMadsen** [comment]
Ah, I missunderstod. I though the error happened on initialization, but it actually happens when http://localhost:3343 is opened. Thus it is not the `JSON.parse` part that causes the error.

This gave me the hunch that maybe it was `babelify` that choked on parsing the dump file. I think this was correct, after setting babelify up to ignorering the dump file I can't reproduce the error.

Could you try out dprof v0.18.2 and see if it works?

**Comment by Fishrock123** [comment]
Nice. I ran into this with *very* large npm output.
