### ISSUE TITLE
this is undefined in visualizer

### ISSUE THREAD

**Issue by naugtur** [AndreasMadsen/dprof#26]
dprof 1.0.1
visualizer.build.js 14
`d3_document = this.document`

Somehow `this` is undefined, looks like some new tricks in build tools. 
Throws the same in FF and Chromium

**Comment by naugtur** [comment]
update: d3 doesn't work in strict mode. `"use strict"` is added automatically by the build system.

**Comment by AndreasMadsen** [comment]
Hmm, I can't reproduce. Could you show the exact steps you are doing?

Could you also try the interactive example in https://dprof.js.org

**Comment by naugtur** [comment]
Checked. The online version works. 

although not on a gz file produced by dprof locally, I had to extract it first and had issues extracting at first

**Comment by naugtur** [comment]
Tried with an extracted file and it works locally too. The problem is in gz produced by dprof on node8. I'll look into it and maybe report a new issue if I find out what's happening.

**Comment by naugtur** [comment]
Found it. Here's how you reproduce the 'undefined' issue:

```
zcat dprof.json.gz | node node_modules/.bin/dprof
```

It's not documented to work like that, so I'm not reopening.
