### ISSUE TITLE
Doesn't work in Safari

### ISSUE THREAD

**Issue by watson** [AndreasMadsen/dprof#5]
Using the example program from the readme, this is the output in Safari:

![screen shot 2015-11-04 at 13 04 27](https://cloud.githubusercontent.com/assets/10602/10937644/a83445d4-82f4-11e5-9337-c287766d5c7a.png)

This is the output in Chrome:

![screen shot 2015-11-04 at 13 04 34](https://cloud.githubusercontent.com/assets/10602/10937647/b0abb774-82f4-11e5-96f4-a88ae051858f.png)

Looking in the Safari console I think I see the culprit:

![screen shot 2015-11-04 at 13 06 24](https://cloud.githubusercontent.com/assets/10602/10937672/e2443cd4-82f4-11e5-98e6-bc2ce95cd313.png)

**Comment by AndreasMadsen** [comment]
Yeah, I don't really care about browser compatibility at this stage, there is enough work in just filling async-wrap issues.

Any suggestions, that doesn't involve a full rewrite / search and replace.

**Comment by watson** [comment]
@AndreasMadsen Yeah, I know it's WIP - especially the visualizer - so I just wanted to document it with an issue so that others didn't spend time wondering why their browser is blank.

I'm not a front end guy, but I would imagine there is no way around this. As far as I understand the error in the console, then if you use `const` you can't also run in strict mode. So either disable that or use `var` instead I guess? Just guessing though. I'll ask around at the office tomorrow :wink:

**Comment by AndreasMadsen** [comment]
I thank a transpiler like babel can be used. But I've never used it my self.
