### ISSUE TITLE
Running dprof without input could automatically find dprof.json.gz in cwd

### ISSUE THREAD

**Issue by Fishrock123** [AndreasMadsen/dprof#9]
When nothing is piped into dprof, I think we could automatically do a search for dprof.json.gz in cwd to increase ease of use...

@AndreasMadsen What do you think?

**Comment by AndreasMadsen** [comment]
Sounds like a good idea, but I'm not sure how that is detected.

**Comment by AndreasMadsen** [comment]
Feature added in 38a3e3ec09f68f64a9a2b128b6e468ea29b23bbd, it detect stdin using `process.stdin.isTTY`.
